### PR TITLE
update retro-movies for updated gym-retro codebase.

### PR DESCRIPTION
**Pull request by joshim5**

### CODE REVIEW

**Comment by christopherhesse** [comment]
Is `get_states.py` supposed to be in here?  It looks like a test script

**Comment by joshim5** [comment]
This is the same script listed in the `README`. To use `retro-movies` to make a new movie and actually 'get the states' you copy/paste those lines and run. It probably makes sense to have this as a standalone file so it can just be run without needing to copy/pate.

**Comment by christopherhesse** [comment]
Okay, want to remove it from the README then? You can do a link directly to the file with markdown like [`get-states.py`](get-states.py)

**Comment by joshim5** [comment]
done, also added some statistics about the movies

**Comment by christopherhesse** [comment]
Thanks!

**Pull request merged**
